//Thanks to Jesmundo for the example list (https://www.jesmundo.co.uk/blogs/hen-party-ideas/hen-night-dares-forfeits-challenges)
//Thanks to matthewb for the list conversion to array (https://www.matthewb.id.au/csv/text-list-to-javascript-array.html)

const actions = [
    'Get a kiss from 5 different guys',
    'Collect 3 pairs of boxer shorts',
    'Kiss a man with a bald head',
    'Down a shot of alcohol which someone else orders',
    'Get a random guy to buy you a drink',
    'Wear your bra outside your clothes for 10 minutes',
    'Go up to a random man and propose',
    'Get a man s glasses, take them from him, put them on and take a selfie',
    'Photobomb at least 3 men s photos',
    'Go up to a man and sing to him',
    'Order a drink in a foreign accent',
    'Talk to a man in a foreign accent and convince him you re from that country',
    'Down 3 shots in a row',
    'Down a cocktail of the hen parties drinks',
    'Down a pint in one',
    'Get a man s business card and leave a message on his answer machine',
    'Talk to a random stranger like you ve known him all your life',
    'Convince a stranger that you re famous',
    'Ask someone for their autograph',
    'Can t say no - For 30 minutes you can t say no to anything',
    'Blow a kiss to a stranger across the room',
    'Get a selfie with a doorman / bouncer',
    'Perform a dance like a cheerleader',
    'Serenade a stranger',
    'Ask a man to serenade you with a song',
    'For 10 minutes you can t speak, and have to sing everything you want to say',
    'Perform gym exercises and work out style dance moves to the music playing',
    'Get a pair of men s boxer shorts and wear them over your clothing',
    'Find a guy who ll let you put your lipstick on him',
    'Hug 5 different men',
    'Get a photo with the hottest man in the room',
    'Get someone to take a photo of you - But with their own camera!',
    'Get a man s phone number, and leave a message on his answer machine',
    'Take a photo with 4 different men who look like they could start a boy band',
    'Say the alphabet backwards',
    'Fake an orgasm',
    'Do 10 press ups in public',
    'Do some yoga poses',
    'Get a man to talk dirty to you',
    'Go up to a man and talk dirty to him',
    'Give a piggy back ride to someone',
    'Dance on a table or stand on a chair',
    'Take off your bra without removing your top',
    'Get a photo with a barman',
    'Stand on one leg and count to 20 out loud',
    'Swap an item of clothing with a man',
    'Do an impersonation of someone famous',
    'Have your photo taken with a policeman or someone in uniform',
    'Dance to the birdie song or the Macarena',
    'Remove a man s belt without using your hands',
];
export default actions;
